apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

patchesJson6902:
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: guestbook-ui
  path: ingress-patches.yaml