apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bradkwadsworth-mw/argocd-getting-started.git
    targetRevision: HEAD
    path: guestbook/local
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook