apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 15.1.3
    path: wordpress
    helm:
      parameters:
      - name: service.type
        value: ClusterIP
      - name: ingress.enabled
        value: "true"
      - name: ingress.hostname
        value: wordpress-127.0.0.1.sslip.io
      - name: ingress.tls
        value: "true"
      - name: ingress.selfSigned
        value: "true"
      - name: wordpressUsername
        value: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
