apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/bradkwadsworth-mw/argocd-getting-started.git
    targetRevision: HEAD
    path: wordpress
    helm:
      valueFiles:
      - ../helm-values/wordpress/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
